version: "3.7"

services:
  db:
    container_name: fwallsbot_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  django: &django
    container_name: fwallsbot_django
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput &&
                    gunicorn core.wsgi:application --bind 0.0.0.0:${DJANGO_WEB_PORT} --workers=4"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
      - ./locale:/home/app/web/locale
      - ./logs:/home/app/web/logs
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - ${DJANGO_WEB_PORT}:${DJANGO_WEB_PORT}
    depends_on:
      - db

  bot:
    container_name: fwallsbot_bot
    <<: *django
    command: "python main.py"
    ports:
      - 8003:8003

volumes:
  postgres_data: