version: "3.7"

services:
  postgres:
    container_name: fwallsbot_postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  django:
    container_name: fwallsbot_django
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput &&
                    gunicorn core.wsgi:application --bind 0.0.0.0:${DJANGO_WEB_PORT} --workers=4"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
      - ./locale:/home/app/web/locale
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    depends_on:
      - postgres

volumes:
  postgres_data:
  