# Generated by Django 5.0.2 on 2024-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Айди юзера')),
            ],
            options={
                'verbose_name': 'Админ',
                'verbose_name_plural': 'Админы',
            },
        ),
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID файла')),
                ('url', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('forward_message_id', models.IntegerField(blank=True, null=True, verbose_name='Переслан с канала')),
                ('downloads', models.IntegerField(default=0, verbose_name='Количество загрузок ру')),
                ('unique_downloads', models.IntegerField(default=0, verbose_name='Количество уникальных загрузок ру')),
                ('downloads_second', models.IntegerField(default=0, verbose_name='Количество загрузок уз')),
                ('unique_downloads_second', models.IntegerField(default=0, verbose_name='Количество уникальных загрузок уз')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='TGusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(verbose_name='ID юзера')),
                ('language', models.TextField(verbose_name='Язык')),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Пользователя бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
