# Generated by Django 5.0.3 on 2024-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Russian'), ('uz', 'Uzbek')], max_length=2, null=True),
        ),
    ]
