# Generated by Django 5.0.2 on 2024-03-19 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, verbose_name='ID файла')),
                ('file_content_type', models.CharField(max_length=255, verbose_name='Тип файла')),
                ('file_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.filemessage')),
            ],
        ),
    ]
