# Generated by Django 5.0.3 on 2024-03-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_telegramuser_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='language',
            new_name='language_code',
        ),
    ]
