# Generated by Django 5.0.2 on 2024-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_mediagroupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemessage',
            name='is_media_group',
            field=models.BooleanField(default=False, verbose_name='Медиа группа'),
        ),
    ]
