# Generated by Django 5.0.3 on 2024-03-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_filemessage_is_media_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Temp Admin', 'verbose_name_plural': 'Temp Admins'},
        ),
        migrations.AlterModelOptions(
            name='filemessage',
            options={'verbose_name': 'Temp FileMessage', 'verbose_name_plural': 'Temp FileMessages'},
        ),
        migrations.AlterModelOptions(
            name='mediagroupitem',
            options={'verbose_name': 'Temp MediaGroupItem', 'verbose_name_plural': 'Temp MediaGroupItems'},
        ),
        migrations.AlterModelOptions(
            name='tgusers',
            options={'verbose_name': 'Temp TGusers', 'verbose_name_plural': 'Temp TGusers'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='downloads_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='forward_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='is_media_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='unique_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filemessage',
            name='unique_downloads_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediagroupitem',
            name='file_content_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mediagroupitem',
            name='file_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='language',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='user_id',
            field=models.TextField(),
        ),
    ]
